
# After registering a name on build.snapcraft.io, commit an uncommented line:
name: interactive-data-editor
version: '2.9.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: A Software to interactively edit data in a graphical manner. # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

architectures:
  - build-on: amd64
  - build-on: i386
  
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  - browser-support
  - cups-control
  - home
  - network
  - opengl
  - pulseaudio
  - removable-media
  - unity7
  - desktop
  - desktop-legacy
  - gsettings
  - wayland
  - x11